#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Hubs,  S2, HTServo,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     rightback,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     rightfront,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     lift,          tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     leftback,      tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_2,     leftfront,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C4_1,     belt,          tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C4_2,     motorK,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C1_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////
//Omnidrive for one driver
//Left motors must be reversed
/////////////////////////////////////////////////////////

//INCLUDE
#include "JoystickDriver.c"  //I edited out the write to screen section of the driver

//DEFINE
#define joy1x1 joystick.joy1_x1////////
#define joy1x2 joystick.joy1_x2////////
#define joy1y1 joystick.joy1_y1////////
#define joy1y2 joystick.joy1_y2////////
#define joy2x1 joystick.joy2_x1////////
#define joy2x2 joystick.joy2_x2////////
#define joy2y1 joystick.joy2_y1////////
#define joy2y2 joystick.joy2_y2////////

int deadzone = 15; //Joystick dead zone for faulty joysticks
float rfspeed, rbspeed, lfspeed, lbspeed; //Variables for various motors to equal. Not required, but simplifies code

int sprintdivisorvalue = 2; //Caeser goes x times slower when the sprint button isn't pressed.
int sprintdivisor; //Changed in code.

void omnidrive(){ //OMNI-All directional drive with sprint
								  //button and reversed left motors
	rfspeed = (joy1y1-joy1x1-joy1x2)/sprintdivisor;
	rbspeed = (joy1y1+joy1x1-joy1x2)/sprintdivisor;
	lfspeed = (joy1y1+joy1x1+joy1x2)/sprintdivisor;
	lbspeed = (joy1y1-joy1x1+joy1x2)/sprintdivisor;
}

////MAIN/////////////////////////////////////////////////

task main()
{
  waitForStart();

 while (true){
	 getJoystickSettings(joystick);

////JOYSTICK DEADZONES///////////////////////////////////
//With omnidrive, deadzones can't be used in the
//conditional statements, so must be set manually

  	if(abs(joy1y1) < deadzone){
  		 joy1y1 = 0;
  	}
 		else {
 			joy1y1 = joy1y1;
 		}
 		if(abs(joy1x1) < deadzone){
  		 joy1x1 = 0;
  	}
 		else {
 			joy1x1 = joy1x1;
 		}
 		if(abs(joy1x2) < deadzone){
  		 joy1x2 = 0;
  	}
 		else {
 			joy1x2 = joy1x2;
 		}
//////Lift, Sweep and Pulleys////////////////////////////
	 
	if(joy2Btn(1) == 1){
			motor[belt] = 100*(127/100);
 		}
	if(joy2Btn(2) == 1){
			motor[belt] = 0);
 		}	
	
	if(abs(joy2y2) > deadzone){
    	motor[sweep] = (joy2y2)*100/127);
    }

	if(abs(joy2y1) > deadzone){
    	motor[lift] = (joy2y1)*100/127);
    }
	 
/////////////////////////////////////////////////////////

 		if(joy1Btn(8) == 1){
			sprintdivisor = (127/100);
 		}
 		else {
			sprintdivisor = ((127*sprintdivisorvalue)/100);
		}

		omnidrive();

		motor[rightfront] = rfspeed;
		motor[rightback] = rbspeed;
		motor[leftback] = lbspeed;
		motor[leftfront] = lfspeed;

		//Servo Demonstration
/*
		if(joy1Btn(1) == 1){
			servo(contservo) = 250;
 		}
 		if(joy1Btn(2) == 1){
			servo(contservo) = 4;
 		}

		if(joy1Btn(6) == 1){
			servo[stdservo] = 210;
 		}
 		if(joy1Btn(8) == 1){
			servo[stdservo] = 44;
 		}
 		if(joy1Btn(3) == 1){
			servo[stdservo] = 128;
		}*/
  }
}
